# Generated by Django 3.1.1 on 2020-09-18 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20200918_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='startDate',
            field=models.DateField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
